### PR TITLE
Pack update - Fixes errors seen during packer builds

### PR DESCRIPTION
**Pull request by nmaludy**
Added try, except block to catch build errors so that the full run stdout can be displayed for debugging the same way it is displayed when successful.

build error before:
```
STDOUT:
vsphere-iso output will be in this color.

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mount ISO images...
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying file: /file/atest.cfg
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : []
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-i... (353969 more, please see e.stdout)

  STDERR:
```

Dropped the ANSI Escape Sequences on build output to fix error with displaying builds that include inspect tests.

error before:
```
'''ascii'' codec can''t encode character u''✔'' in position 350801: ordinal not in range(128)'
  traceback: "  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 127, in _do_run
    (status, result, context) = runner.run(action_params)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_runner.py", line 267, in run
    return self._get_output_values(exit_code, stdout, stderr, timed_out)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_runner.py", line 328, in _get_output_values
    LOG.warning('Failed to de-serialize result "%s": %s' % (str(action_result), str(e)))
```

Added tests for all python files. Because of implementing testing the `inspect.py` for the `inspect action` had to be renamed to `inspect_action.py` due to a conflicting name import in the nose module.

error:
```
Running tests...
Traceback (most recent call last):
  File "/home/circleci/virtualenv/bin/nosetests", line 6, in <module>
    from nose import run_exit
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/nose/config.py", line 9, in <module>
    from nose.plugins.manager import NoPlugins
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/nose/plugins/__init__.py", line 185, in <module>
    from nose.plugins.manager import *
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/nose/plugins/manager.py", line 418, in <module>
    import pkg_resources
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    ws = cls()
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in __init__
    self.add_entry(entry)
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1873, in find_distributions
    finder = _find_adapter(_distribution_finders, importer)
  File "/home/circleci/virtualenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3039, in _find_adapter
    types = _always_object(inspect.getmro(getattr(ob, '__class__', type(ob))))
AttributeError: module 'inspect' has no attribute 'getmro'
```

The action is still called inspect and works in the same manor as before:
```
# st2 run packer.inspect packerfile="/test/path/template.json"
.
id: 5c50cb0f32a497892e29f586
status: succeeded
parameters: 
  packerfile: /test/path/template.json
result: 
  exit_code: 0
  result:
    builders:
    - name: vsphere-iso
      type: vsphere-iso
    provisioners:
    - type: shell
    - type: shell
    - type: inspec
    - type: shell
    variables: []
  stderr: ''
  stdout: ''
```

### CODE REVIEW

**Comment by nmaludy** [comment]
@LindsayHill looks like CircleCI integration is messed up on repo. Doesn't look like a build was triggered.

**Comment by LindsayHill** [comment]
@nmaludy It's something related to PRs from your repo(s) where you already have CircleCI enabled. CircleCI decides it doesn't need to do the run again, but it also doesn't report results here. 

I don't know if there are CircleCI options we could tweak here to change that behavior

**Comment by nmaludy** [comment]
Hmm i don't see an option for it in the CircleCI settings. Maybe it is smart enough to know when something has already been run through CI and not build it again?

**Comment by LindsayHill** [comment]
I couldn't find anything relevant in CircleCI settings, or general googling around.

> Maybe it is smart enough to know when something has already been run through CI and not build it again?

I'm pretty sure that's what's going on. But I don't know how to get it to display those status results here.

**Comment by LindsayHill** [comment]
The other thing I want to fix is to stop it trying to run the `deploy:` step when the owner is not StackStorm-Exchange. There's no simple way to do that with CircleCI 2.0. There was with 1.0.

There are workarounds, e.g. check environment to see if it's a pull request. But it's a bit ugly.

**Comment by nmaludy** [comment]
wonder if we could get the organization name or something? try to match against StackStorm-Exchange?

**Comment by LindsayHill** [comment]
right, you used to be able to do this with `filter:` and `owner:`. But now you have to do it with env vars. 

See https://discuss.circleci.com/t/how-to-set-the-owner-filter-in-circle-ci-2-0/20443/6

**Pull request merged**
